### PR TITLE
Updated styling of the components, scaling, themed

### PR DESCRIPTION
**Pull request by maalos**
Updated styling and type of the components, fixed scaling across all horizontal screens, Nord themed

### CODE REVIEW

**Comment by maalos** [comment]
lmk if you've got any issues with the styling with all the TypeScript code running since I currently am unable to test it that way

**Comment by Oakchris1955** [comment]
I like how you styled the page. It supports resizing now!!! I just have 2 small requests
1) The font size seems a little big to me. Maybe lowering it to `1.7 vw` would do
2) On the `Table` tab, the unblock buttons are still white 
table_image

**Comment by Oakchris1955** [comment]
Removed last 2 commits

**Comment by maalos** [comment]
nah dawgg my git skills are horrible... i think that everything that had to be done in this PR has been done

**Pull request merged**
